"""crear tabla track_stats

Revision ID: 398f42bb1130
Revises: d8ebeadfa2fe
Create Date: 2026-10-06 01:31:44.107421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398f42bb1130'
down_revision: Union[str, Sequence[str], None] = 'd8ebeadfa2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'title', 'artist', name='uq_guild_track_stat')
    )
    op.create_index(op.f('ix_track_stats_artist'), 'track_stats', ['artist'], unique=False)
    op.create_index(op.f('ix_track_stats_guild_id'), 'track_stats', ['guild_id'], unique=False)
    op.create_index(op.f('ix_track_stats_title'), 'track_stats', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_stats_title'), table_name='track_stats')
    op.drop_index(op.f('ix_track_stats_guild_id'), table_name='track_stats')
    op.drop_index(op.f('ix_track_stats_artist'), table_name='track_stats')
    op.drop_table('track_stats')
    # ### end Alembic commands ###
