"""crear tablas iniciales guild y playlists

Revision ID: d8ebeadfa2fe
Revises: fc5adaedd2c6
Create Date: 2026-10-06 00:29:40.828523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ebeadfa2fe'
down_revision: Union[str, Sequence[str], None] = 'fc5adaedd2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
