"""crear tablas iniciales guild y playlists

Revision ID: fc5adaedd2c6
Revises: 
Create Date: 2026-10-06 00:00:19.239780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5adaedd2c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('dj_role_id', sa.BigInteger(), nullable=True),
    sa.Column('music_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('default_volume', sa.SmallInteger(), nullable=False),
    sa.Column('autoplay_enabled', sa.Boolean(), nullable=False),
    sa.Column('inactivity_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('custom_playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'creator_id', 'name', name='uq_guild_creator_playlist_name')
    )
    op.create_index(op.f('ix_custom_playlists_creator_id'), 'custom_playlists', ['creator_id'], unique=False)
    op.create_index(op.f('ix_custom_playlists_guild_id'), 'custom_playlists', ['guild_id'], unique=False)
    op.create_index(op.f('ix_custom_playlists_name'), 'custom_playlists', ['name'], unique=False)
    op.create_table('playlist_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['custom_playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_items_playlist_id'), 'playlist_items', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_items_playlist_id'), table_name='playlist_items')
    op.drop_table('playlist_items')
    op.drop_index(op.f('ix_custom_playlists_name'), table_name='custom_playlists')
    op.drop_index(op.f('ix_custom_playlists_guild_id'), table_name='custom_playlists')
    op.drop_index(op.f('ix_custom_playlists_creator_id'), table_name='custom_playlists')
    op.drop_table('custom_playlists')
    op.drop_table('guild_configs')
    # ### end Alembic commands ###
